# 1. Database Connection Settings with Docker Environment Fallbacks
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fintech_wallet?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. JWT Security Configurations (Custom settings for our tokens)
jwt.secret=ThisIsMySuperSecretFintechLedgerWalletKey2026
jwt.expiration=86400000

# 4. Server Port
server.port=8080

# Allow the connection pool to scale up to support multiple parallel testing threads
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

# 5. Redis Cache Configuration with Docker Environment Fallbacks
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
# Set a 10-minute automatic expiration safety window for cached items (in milliseconds)
spring.data.redis.time-to-live=600000