
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://admin:rtmhRssP7w0X7xqFi42ebdqepJS989ME@dpg-d8l5v5km0tmc738tpjv0-a.singapore-postgres.render.com:5432/fintech_wallet_y1ax}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rtmhRssP7w0X7xqFi42ebdqepJS989ME}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# 2. JPA & Hibernate Configuration
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# 3. JWT Security Configurations
# ===================================================================
jwt.secret=ThisIsMySuperSecretFintechLedgerWalletKey2026
jwt.expiration=86400000

# ===================================================================
# 4. Server Port (CRITICAL FOR RENDER)
# ===================================================================
server.port=${PORT:8080}

# HikariCP Connection Pool Scaling
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

# ===================================================================
# 5. Redis Cache Configuration
# ===================================================================
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.cache.type=redis
spring.data.redis.time-to-live=600000

# ===================================================================
# 6. OpenAPI / Swagger Documentation Paths
# ===================================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=methods

spring.security.user.name=admin
spring.security.user.password=admin123

# ===================================================================
# 7. Free Cloud AI via Groq
# ===================================================================
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile