name: Java CI/CD Pipeline with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# This turns on Node.js 24 explicitly to clear out the warning message!
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Java 21 environment
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    # Using the -f flag forces Maven to find the pom.xml inside wallet/ no matter what
    - name: Build and Test with Maven
      run: mvn clean verify -f wallet/pom.xml

    - name: Deploy to Render
      if: success()
      run: |
        curl -X POST "https://api.render.com/deploy/srv-d8l5ko3eo5us73b46co0?key=riJPaWRZBy4"