name: Java CI/CD Pipeline with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# This turns on Node.js 24 explicitly to clear out the warning message!
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Java 21 environment
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    # Using the -f flag forces Maven to find the pom.xml inside wallet/ no matter what
    - name: Build and Test with Maven
      env:
        GROQ_API_KEY: "gsk_v1_mockkeyforcitestingenvironmentpurposesonly12345"
        SPRING_AI_OPENAI_API_KEY: "gsk_v1_mockkeyforcitestingenvironmentpurposesonly12345"
      run: mvn clean verify -f wallet/pom.xml

    - name: Deploy to Render
      if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"